spring:
  application:
    name: COA-Ledger
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/gtelpay_prod}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:gtel-c-server}
    password: ${RABBITMQ_PASSWORD:password}
    virtual-host: ${RABBITMQ_VHOST:/gtel-prod}
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}

server:
  port: 8090
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    dev.nivic: DEBUG
