## Automatic clustering via peer discovery
cluster_formation.peer_discovery_backend = rabbit_peer_discovery_classic_config
cluster_formation.classic_config.nodes.1 = rabbit@rabbitmq-node-1
cluster_formation.classic_config.nodes.2 = rabbit@rabbitmq-node-2
cluster_formation.classic_config.nodes.3 = rabbit@rabbitmq-node-3

## Retry until all peers are reachable
cluster_formation.discovery_retry_limit    = 10
cluster_formation.discovery_retry_interval = 3000

## Remove unreachable nodes from the cluster record after restart
cluster_formation.node_cleanup.interval         = 30
cluster_formation.node_cleanup.only_log_warning = true
