// Package merchant is the official Go SDK for accepting Saving payments.
//
// It wraps the Merchants Host HTTP API and provides Ed25519 signature
// verification so you can authenticate payment QRs offline.
//
// Quick start:
//
//	client := merchant.NewClient("https://merchants.example.com", mid, token)
//
//	order, err := client.CreateOrder(ctx, merchant.OrderRequest{
//	    Amount: 50_000,
//	    Note:   "Cà phê x2",
//	})
//	// order.QRCode → "saving://pay?pr=..."
//	// display as QR to customer
//
//	paid, err := client.WaitForPayment(ctx, order.OrderID, 10*time.Minute)
package merchant

import (
	"bytes"
	"context"
	"crypto/ed25519"
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"
)

// ─── Types ────────────────────────────────────────────────────────────────────

// OrderRequest is the input to CreateOrder.
type OrderRequest struct {
	Amount  uint64 // in VND đồng
	Note    string // optional, shown to payer
	OrderID string // optional; generated by server when empty
}

// Order is returned by CreateOrder and GetOrder.
type Order struct {
	OrderID   string
	Amount    uint64
	Note      string
	Status    string // "pending" | "paid" | "expired"
	CreatedAt int64  // unix milliseconds
	PaidAt    *int64
	PaidBy    *uint32
	QRCode    string // "saving://pay?pr=..." — only set by CreateOrder
}

// Stats is returned by GetStats.
type Stats struct {
	TotalEarned uint64
	OrderCount  int
}

// PaymentRequest is the signed payload embedded in every QR code.
// It can be verified offline with VerifyPaymentRequest.
type PaymentRequest struct {
	MID     uint32 `json:"mid"`
	OrderID string `json:"order_id"`
	Amount  uint64 `json:"amount"`
	TS      int64  `json:"ts"`  // unix milliseconds; expires after 10 min
	Sig     string `json:"sig"` // base64(ed25519 sig, 64 bytes)
}

// ─── Client ───────────────────────────────────────────────────────────────────

// Client calls the Merchants Host API on behalf of one merchant.
type Client struct {
	baseURL string
	mid     uint32
	token   string
	hc      *http.Client
}

// NewClient creates a client for merchant mid authenticated with token.
// baseURL is the Merchants Host root (e.g. "http://localhost:8090").
func NewClient(baseURL string, mid uint32, token string) *Client {
	return &Client{
		baseURL: baseURL,
		mid:     mid,
		token:   token,
		hc:      &http.Client{Timeout: 15 * time.Second},
	}
}

// CreateOrder creates a new payment order and returns a QR code URL.
func (c *Client) CreateOrder(ctx context.Context, req OrderRequest) (*Order, error) {
	body := map[string]any{"amount": req.Amount, "note": req.Note}
	if req.OrderID != "" {
		body["order_id"] = req.OrderID
	}
	var resp struct {
		OrderID string `json:"order_id"`
		PR      string `json:"pr"`
		QRURL   string `json:"qr_url"`
	}
	if err := c.do(ctx, http.MethodPost,
		fmt.Sprintf("/merchants/%d/orders", c.mid), body, &resp); err != nil {
		return nil, err
	}
	return &Order{
		OrderID: resp.OrderID,
		Amount:  req.Amount,
		Note:    req.Note,
		Status:  "pending",
		QRCode:  resp.QRURL,
	}, nil
}

// GetOrder fetches the current state of an order.
func (c *Client) GetOrder(ctx context.Context, orderID string) (*Order, error) {
	var raw struct {
		ID        string  `json:"id"`
		Amount    uint64  `json:"amount"`
		Note      string  `json:"note"`
		Status    string  `json:"status"`
		CreatedAt int64   `json:"created_at"`
		PaidAt    *int64  `json:"paid_at"`
		PaidBy    *uint32 `json:"paid_by"`
	}
	if err := c.do(ctx, http.MethodGet,
		fmt.Sprintf("/merchants/%d/orders/%s", c.mid, orderID), nil, &raw); err != nil {
		return nil, err
	}
	return &Order{
		OrderID:   raw.ID,
		Amount:    raw.Amount,
		Note:      raw.Note,
		Status:    raw.Status,
		CreatedAt: raw.CreatedAt,
		PaidAt:    raw.PaidAt,
		PaidBy:    raw.PaidBy,
	}, nil
}

// ListOrders returns up to 50 most recent orders for this merchant.
func (c *Client) ListOrders(ctx context.Context) ([]*Order, error) {
	var raw []struct {
		ID        string  `json:"id"`
		Amount    uint64  `json:"amount"`
		Note      string  `json:"note"`
		Status    string  `json:"status"`
		CreatedAt int64   `json:"created_at"`
		PaidAt    *int64  `json:"paid_at"`
		PaidBy    *uint32 `json:"paid_by"`
	}
	if err := c.do(ctx, http.MethodGet,
		fmt.Sprintf("/merchants/%d/orders", c.mid), nil, &raw); err != nil {
		return nil, err
	}
	orders := make([]*Order, len(raw))
	for i, r := range raw {
		orders[i] = &Order{
			OrderID:   r.ID,
			Amount:    r.Amount,
			Note:      r.Note,
			Status:    r.Status,
			CreatedAt: r.CreatedAt,
			PaidAt:    r.PaidAt,
			PaidBy:    r.PaidBy,
		}
	}
	return orders, nil
}

// GetStats returns total earnings and paid order count for this merchant.
func (c *Client) GetStats(ctx context.Context) (*Stats, error) {
	var raw struct {
		TotalEarned uint64 `json:"total_earned"`
		OrderCount  int    `json:"order_count"`
	}
	if err := c.do(ctx, http.MethodGet,
		fmt.Sprintf("/merchants/%d/stats", c.mid), nil, &raw); err != nil {
		return nil, err
	}
	return &Stats{TotalEarned: raw.TotalEarned, OrderCount: raw.OrderCount}, nil
}

// WaitForPayment polls GetOrder until the order is paid or timeout elapses.
// Returns the paid order, or an error if it times out or fails.
func (c *Client) WaitForPayment(ctx context.Context, orderID string, timeout time.Duration) (*Order, error) {
	deadline := time.Now().Add(timeout)
	interval := 1 * time.Second
	for {
		if time.Now().After(deadline) {
			return nil, fmt.Errorf("merchant: timeout waiting for payment on %s", orderID)
		}
		order, err := c.GetOrder(ctx, orderID)
		if err != nil {
			return nil, err
		}
		if order.Status == "paid" {
			return order, nil
		}
		if order.Status == "expired" {
			return nil, fmt.Errorf("merchant: order %s expired", orderID)
		}
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-time.After(interval):
			if interval < 5*time.Second {
				interval += 500 * time.Millisecond
			}
		}
	}
}

// ─── Offline helpers ──────────────────────────────────────────────────────────

// ParsePaymentRequest decodes a base64url-encoded payment request from a QR URL.
// qrURL is either "saving://pay?pr=<payload>" or just the raw base64url payload.
func ParsePaymentRequest(qrURL string) (*PaymentRequest, error) {
	payload := qrURL
	if len(qrURL) > 15 && qrURL[:15] == "saving://pay?pr=" {
		payload = qrURL[15:]
	}
	// Restore standard base64 padding
	for len(payload)%4 != 0 {
		payload += "="
	}
	b64 := payload
	for i := 0; i < len(b64); i++ {
		switch b64[i] {
		case '-':
			b64 = b64[:i] + "+" + b64[i+1:]
		case '_':
			b64 = b64[:i] + "/" + b64[i+1:]
		}
	}
	data, err := base64.StdEncoding.DecodeString(b64)
	if err != nil {
		return nil, fmt.Errorf("merchant: decode base64: %w", err)
	}
	var pr PaymentRequest
	if err := json.Unmarshal(data, &pr); err != nil {
		return nil, fmt.Errorf("merchant: unmarshal payment request: %w", err)
	}
	return &pr, nil
}

// VerifyPaymentRequest verifies the Ed25519 signature on a payment request
// using the merchant's public key (base64-standard encoded, 32 bytes).
// This check is fully offline — no HTTP call required.
func VerifyPaymentRequest(pr *PaymentRequest, pubkeyB64 string) error {
	pub, err := base64.StdEncoding.DecodeString(pubkeyB64)
	if err != nil || len(pub) != ed25519.PublicKeySize {
		return fmt.Errorf("merchant: invalid pubkey")
	}
	sig, err := base64.StdEncoding.DecodeString(pr.Sig)
	if err != nil || len(sig) != ed25519.SignatureSize {
		return fmt.Errorf("merchant: invalid signature encoding")
	}
	if !ed25519.Verify(ed25519.PublicKey(pub), signedMsg(pr), sig) {
		return fmt.Errorf("merchant: signature invalid")
	}
	age := time.Since(time.UnixMilli(pr.TS))
	if age > 10*time.Minute || age < -time.Minute {
		return fmt.Errorf("merchant: payment request expired (age %s)", age.Round(time.Second))
	}
	return nil
}

// signedMsg produces the canonical message that was signed:
//
//	mid(4 BE) || amount(8 BE) || ts(8 BE) || order_id(utf-8)
func signedMsg(pr *PaymentRequest) []byte {
	msg := make([]byte, 4+8+8+len(pr.OrderID))
	binary.BigEndian.PutUint32(msg[0:], pr.MID)
	binary.BigEndian.PutUint64(msg[4:], pr.Amount)
	binary.BigEndian.PutUint64(msg[12:], uint64(pr.TS))
	copy(msg[20:], pr.OrderID)
	return msg
}

// ─── HTTP helper ──────────────────────────────────────────────────────────────

func (c *Client) do(ctx context.Context, method, path string, body any, out any) error {
	var r io.Reader
	if body != nil {
		b, _ := json.Marshal(body)
		r = bytes.NewReader(b)
	}
	req, err := http.NewRequestWithContext(ctx, method, c.baseURL+path, r)
	if err != nil {
		return err
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	req.Header.Set("X-Merchant-Token", c.token)

	resp, err := c.hc.Do(req)
	if err != nil {
		return fmt.Errorf("merchant: http: %w", err)
	}
	defer resp.Body.Close()
	data, _ := io.ReadAll(resp.Body)

	if resp.StatusCode >= 400 {
		var e struct {
			Error string `json:"error"`
		}
		json.Unmarshal(data, &e)
		if e.Error != "" {
			return fmt.Errorf("merchant: %s", e.Error)
		}
		return fmt.Errorf("merchant: HTTP %d", resp.StatusCode)
	}
	if out != nil {
		if err := json.Unmarshal(data, out); err != nil {
			return fmt.Errorf("merchant: decode response: %w", err)
		}
	}
	return nil
}
