package sevlet_test

// Cross-language interoperability tests.
//
// Golden vectors are generated by GoldenVectorPrinter.java (in the Java tree)
// using the fixed secret and the same constants as HotPathTest.java:
//
//   secret    = "cross-check-secret-32-bytes-pad!" (ASCII, 32 bytes)
//   MID       = 42
//   REQUEST_ID= 1000
//   ORDER_ID  = 999
//   AMOUNT    = 50 000
//   DEBIT     = 1  /  CREDIT = 2
//
// Run: mvn test -Dtest="GoldenVectorPrinter#printTransferVector"
// to regenerate if the wire layout changes.

import (
	"bytes"
	"encoding/hex"
	"strings"
	"testing"

	"nivic.dev/saving/sdk/sevlet"
)

// ─── Fixed inputs (mirrors HotPathTest.java constants) ───────────────────────

var (
	crossSecret = []byte("cross-check-secret-32-bytes-pad!") // 32 bytes

	crossMID       = uint64(42)
	crossReqID     = uint64(1000)
	crossOrdID     = uint64(999)
	crossAmount    = uint64(50_000)
	crossDebit     = uint32(1)
	crossCredit    = uint32(2)
)

// ─── Golden hex strings from Java ────────────────────────────────────────────

const (
	// GoldenVectorPrinter output — TRANSFER, empty extraData, 83 bytes
	goldenTransferHex = "0000000000000000000000000000000000002A00000000000003E800000000000003E7000000000000C35000000001000000022D7ACEF456B7E522B7C4DDD7972E48BBAA8377E12DBACE943501D99F118A330B"
	goldenTransferSigHex = "2D7ACEF456B7E522B7C4DDD7972E48BBAA8377E12DBACE943501D99F118A330B"

	// CONFIRM_PAYMENT: requestId=2000, extraData = requestId(8)+challenge(32, all 0x07)
	goldenConfirmHex = "0000000000000000000001000000000000002A00000000000007D000000000000003E7000000000000C350000000010000000200000000DEADBEEF07070707070707070707070707070707070707070707070707070707070707078C429C5D328A102D110E6A27958B3A964C58529852A85CB2E9CEB6F5EBACDF8C"
	goldenConfirmSigHex = "8C429C5D328A102D110E6A27958B3A964C58529852A85CB2E9CEB6F5EBACDF8C"

	// ConfirmPayloadParserTest.v0PrefixMatchesChallengeAndAllowsTlvTail
	// extra = origRequestId(0xDEADBEEF, 8B) | challenge(0x07*32) | tail(0x2A*12)
	goldenConfirmExtraHex = "00000000DEADBEEF07070707070707070707070707070707070707070707070707070707070707072A2A2A2A2A2A2A2A2A2A2A2A"
)

func mustDecodeHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(strings.ToLower(s))
	if err != nil {
		t.Fatalf("hex decode %q: %v", s, err)
	}
	return b
}

// ─── Layout constants cross-check ────────────────────────────────────────────

// TestCrossConstantsMatchJava verifies Go constants match SevletWalletCodec.java.
//
//   PREFIX_BEFORE_EXTRA_LEN = 51   (HEADER_PADDING_LEN=3 + 8+8+8+8+8+4+4)
//   SIG_LEN                 = 32
//   MIN_WIRE_LEN            = 83
func TestCrossConstantsMatchJava(t *testing.T) {
	if sevlet.MinWire != 83 {
		t.Errorf("MinWire = %d; Java MIN_WIRE_LEN = 83", sevlet.MinWire)
	}
	n, _ := sevlet.ExtraDataLength(83)
	if n != 0 {
		t.Errorf("ExtraDataLength(83) = %d; want 0 (empty extraData at MIN_WIRE)", n)
	}
	n, _ = sevlet.ExtraDataLength(83 + 40) // 40 = CONFIRM_V0_PREFIX_LEN
	if n != 40 {
		t.Errorf("ExtraDataLength(83+40) = %d; want 40", n)
	}
	if sevlet.ConfirmExtraMinLen != 40 {
		t.Errorf("ConfirmExtraMinLen = %d; Java CONFIRM_V0_PREFIX_LEN = 40", sevlet.ConfirmExtraMinLen)
	}
	if sevlet.DefaultMaxExtraData != 262_144 {
		t.Errorf("DefaultMaxExtraData = %d; Java DEFAULT_MAX_EXTRA_DATA_BYTES = 262144", sevlet.DefaultMaxExtraData)
	}
}

// TestCrossOpcodeValuesMatchJava mirrors WalletInputOp.java constants.
func TestCrossOpcodeValuesMatchJava(t *testing.T) {
	// WalletInputOp.TRANSFER=0, CONFIRM=1, REJECT=2, REVERSAL=3
	cases := []struct{ op uint64; want uint64; name string }{
		{sevlet.OpTransfer,       0, "OpTransfer"},
		{sevlet.OpConfirmPayment, 1, "OpConfirmPayment"},
		{sevlet.OpRejectPayment,  2, "OpRejectPayment"},
		{sevlet.OpReversal,       3, "OpReversal"},
	}
	for _, c := range cases {
		if c.op != c.want {
			t.Errorf("%s = %d; Java says %d", c.name, c.op, c.want)
		}
	}
}

// ─── Golden vector: TRANSFER ──────────────────────────────────────────────────

// TestCrossTransferGoMatchesJava verifies that Go Sign produces byte-for-byte
// identical output to the Java SevletWalletClient.sign() / ByteBuffer codec.
func TestCrossTransferGoMatchesJava(t *testing.T) {
	want := mustDecodeHex(t, goldenTransferHex)

	got, err := sevlet.NewTransfer(crossMID, crossReqID, crossOrdID, crossAmount,
		crossDebit, crossCredit, nil, crossSecret)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, want) {
		t.Errorf("Go wire ≠ Java golden\n got: %X\nwant: %X", got, want)
	}
}

// TestCrossTransferGoVerifiesJavaWire verifies that Go Verify accepts the
// exact wire bytes emitted by the Java SevletWalletClient.
func TestCrossTransferGoVerifiesJavaWire(t *testing.T) {
	wire := mustDecodeHex(t, goldenTransferHex)
	ok, err := sevlet.Verify(wire, crossSecret)
	if err != nil || !ok {
		t.Fatalf("Go Verify rejected Java-produced wire: err=%v ok=%v", err, ok)
	}
}

// TestCrossTransferGoDecodesJavaWire verifies all field values after decoding
// the Java-produced wire.
func TestCrossTransferGoDecodesJavaWire(t *testing.T) {
	wire := mustDecodeHex(t, goldenTransferHex)
	p, err := sevlet.Decode(wire)
	if err != nil {
		t.Fatal(err)
	}
	if p.Command   != sevlet.OpTransfer { t.Errorf("command = %d, want %d", p.Command, sevlet.OpTransfer) }
	if p.Mid       != crossMID          { t.Errorf("mid = %d, want %d", p.Mid, crossMID) }
	if p.RequestID != crossReqID        { t.Errorf("requestId = %d, want %d", p.RequestID, crossReqID) }
	if p.OrderID   != crossOrdID        { t.Errorf("orderId = %d, want %d", p.OrderID, crossOrdID) }
	if p.Amount    != crossAmount       { t.Errorf("amount = %d, want %d", p.Amount, crossAmount) }
	if p.Debit     != crossDebit        { t.Errorf("debit = %d, want %d", p.Debit, crossDebit) }
	if p.Credit    != crossCredit       { t.Errorf("credit = %d, want %d", p.Credit, crossCredit) }
	if len(p.ExtraData) != 0            { t.Errorf("extraData len = %d, want 0", len(p.ExtraData)) }
	wantSig := mustDecodeHex(t, goldenTransferSigHex)
	if !bytes.Equal(p.Sig[:], wantSig) {
		t.Errorf("sig mismatch\n got: %X\nwant: %X", p.Sig, wantSig)
	}
}

// TestCrossPeekMidOnJavaWire mirrors SevletWalletCodec.peekMid.
func TestCrossPeekMidOnJavaWire(t *testing.T) {
	wire := mustDecodeHex(t, goldenTransferHex)
	mid, err := sevlet.PeekMid(wire)
	if err != nil || mid != crossMID {
		t.Fatalf("PeekMid = %d err=%v; want %d", mid, err, crossMID)
	}
}

// TestCrossSignedRegionExcludesPad verifies the HMAC input starts at byte 3
// (after the zero pad), matching signedBytesForHmac(raw) in Java.
func TestCrossSignedRegionExcludesPad(t *testing.T) {
	wire := mustDecodeHex(t, goldenTransferHex)

	// Corrupt the 3-byte pad — HMAC must still be valid because pad is unauthenticated.
	wire[0] = 0xFF; wire[1] = 0xFE; wire[2] = 0xFD
	ok, err := sevlet.Verify(wire, crossSecret)
	if err != nil || !ok {
		t.Fatal("pad bytes are unauthenticated (Java signedBytesForHmac starts at OFFSET_COMMAND=3); verify must still pass after pad corruption")
	}

	// But corrupting byte 3 (command[0]) must fail.
	wire[0] = 0 // restore pad
	wire[3] ^= 0xFF
	ok, _ = sevlet.Verify(wire, crossSecret)
	if ok {
		t.Fatal("command byte is authenticated; corruption at offset 3 must invalidate HMAC")
	}
}

// TestCrossTamperedSigRejected mirrors HotPathTest.badHmacRejected.
func TestCrossTamperedSigRejected(t *testing.T) {
	wire := mustDecodeHex(t, goldenTransferHex)
	wire[len(wire)-1] ^= 0xFF // flip last sig byte
	ok, _ := sevlet.Verify(wire, crossSecret)
	if ok {
		t.Fatal("tampered sig must fail (mirrors Java badHmacRejected test)")
	}
}

// ─── Golden vector: CONFIRM_PAYMENT ──────────────────────────────────────────

// TestCrossConfirmGoMatchesJava verifies CONFIRM wire is byte-identical to Java.
func TestCrossConfirmGoMatchesJava(t *testing.T) {
	want := mustDecodeHex(t, goldenConfirmHex)

	var challenge [32]byte
	for i := range challenge { challenge[i] = 0x07 }
	ce := sevlet.ConfirmExtra{
		OriginalRequestID: 0xDEADBEEF,
		Challenge:         challenge,
	}
	got, err := sevlet.NewConfirm(crossMID, 2000, crossOrdID, crossAmount, crossDebit, crossCredit, ce, crossSecret)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, want) {
		t.Errorf("Go CONFIRM ≠ Java golden\n got: %X\nwant: %X", got, want)
	}
}

// TestCrossConfirmGoVerifiesJavaWire verifies Go accepts the Java CONFIRM wire.
func TestCrossConfirmGoVerifiesJavaWire(t *testing.T) {
	wire := mustDecodeHex(t, goldenConfirmHex)
	ok, err := sevlet.Verify(wire, crossSecret)
	if err != nil || !ok {
		t.Fatalf("Go Verify rejected Java CONFIRM wire: err=%v ok=%v", err, ok)
	}
}

// TestCrossConfirmExtraDecodesCorrectly mirrors ConfirmPayloadParserTest.
// extra = origRequestId(0xDEADBEEF,8B) | challenge(0x07*32) | tail(0x2A*12)
func TestCrossConfirmExtraDecodesCorrectly(t *testing.T) {
	extra := mustDecodeHex(t, goldenConfirmExtraHex)

	ce, err := sevlet.DecodeConfirmExtra(extra)
	if err != nil {
		t.Fatal(err)
	}

	// Java: assertEquals(0xDEADBEEFL, ConfirmPayloadParser.originalRequestId(extra))
	if ce.OriginalRequestID != 0xDEADBEEF {
		t.Errorf("OriginalRequestID = 0x%X; want 0xDEADBEEF", ce.OriginalRequestID)
	}

	// Java: assertArrayEquals(challenge, ConfirmPayloadParser.challenge(extra))
	var wantChallenge [32]byte
	for i := range wantChallenge { wantChallenge[i] = 0x07 }
	if ce.Challenge != wantChallenge {
		t.Errorf("Challenge mismatch: got %X, want %X", ce.Challenge, wantChallenge)
	}

	// Tail: 12 bytes of 0x2A
	if len(ce.Tail) != 12 {
		t.Errorf("Tail len = %d; want 12", len(ce.Tail))
	}
	for i, b := range ce.Tail {
		if b != 0x2A {
			t.Errorf("Tail[%d] = 0x%X; want 0x2A", i, b)
		}
	}
}

// TestCrossConfirmExtraEncodesCorrectly: Go EncodeConfirmExtra → DecodeConfirmExtra
// must round-trip with Java's exact byte layout (origRequestId then challenge).
func TestCrossConfirmExtraEncodesCorrectly(t *testing.T) {
	var challenge [32]byte
	for i := range challenge { challenge[i] = 0x07 }
	ce := sevlet.ConfirmExtra{
		OriginalRequestID: 0xDEADBEEF,
		Challenge:         challenge,
		Tail:              bytes.Repeat([]byte{0x2A}, 12),
	}
	got := sevlet.EncodeConfirmExtra(ce)
	want := mustDecodeHex(t, goldenConfirmExtraHex)
	if !bytes.Equal(got, want) {
		t.Errorf("EncodeConfirmExtra ≠ Java extra_hex\n got: %X\nwant: %X", got, want)
	}
}

// ─── Wire field byte-position cross-check ────────────────────────────────────

// TestCrossFieldBytePositionsMatchJava validates field offsets against
// SevletWalletCodec.java: OFFSET_COMMAND=3, OFFSET_MID=11, OFFSET_REQUEST_ID=19,
// OFFSET_ORDER_ID=27, OFFSET_AMOUNT=35, OFFSET_DEBIT=43, OFFSET_CREDIT=47.
func TestCrossFieldBytePositionsMatchJava(t *testing.T) {
	wire := mustDecodeHex(t, goldenTransferHex)

	check64 := func(name string, offset int, want uint64) {
		t.Helper()
		var v uint64
		for i := 0; i < 8; i++ {
			v = (v << 8) | uint64(wire[offset+i])
		}
		if v != want {
			t.Errorf("%s at offset %d: got %d, want %d", name, offset, v, want)
		}
	}
	check32 := func(name string, offset int, want uint32) {
		t.Helper()
		var v uint32
		for i := 0; i < 4; i++ {
			v = (v << 8) | uint32(wire[offset+i])
		}
		if v != want {
			t.Errorf("%s at offset %d: got %d, want %d", name, offset, v, want)
		}
	}

	if wire[0] != 0 || wire[1] != 0 || wire[2] != 0 {
		t.Error("bytes 0-2 must be zero padding (HEADER_PADDING_LEN=3)")
	}
	check64("command",   3,  uint64(sevlet.OpTransfer))  // OFFSET_COMMAND=3
	check64("mid",       11, crossMID)                    // OFFSET_MID=11
	check64("requestId", 19, crossReqID)                  // OFFSET_REQUEST_ID=19
	check64("orderId",   27, crossOrdID)                  // OFFSET_ORDER_ID=27
	check64("amount",    35, crossAmount)                  // OFFSET_AMOUNT=35
	check32("debit",     43, crossDebit)                   // OFFSET_DEBIT=43
	check32("credit",    47, crossCredit)                  // OFFSET_CREDIT=47
	// extraData starts at 51 (PREFIX_BEFORE_EXTRA_LEN), sig at len-32
}
