package dev.nivic.db;

/**
 * Type-safe database constants generated from {@code src/main/resources/db/schema.sql}.
 *
 * <p>Each table has a nested class with column name constants and the table name itself.
 * Generated by {@code gen.sh} — do not edit manually.
 */
public final class DbSchema {

  private DbSchema() {}


  /** Per-merchant HMAC. payment_check_order = order payment: enforce order_id on retries, WAL only (no immediate ledger/journal). */
  public static final String WALLET_MID_SECRET = "wallet_mid_secret";

  public static final class WALLET_MID_SECRET_ {
    public static final String MID = "mid";
    public static final String SECRET_KEY = "secret_key";
    public static final String PAYMENT_CHECK_ORDER = "payment_check_order";
  }

  /** Optional; see dev.nivic.merchant.MerchantConfig. */
  public static final String MERCHANT_CONFIG = "merchant_config";

  public static final class MERCHANT_CONFIG_ {
    public static final String MID = "mid";
    public static final String ENABLED = "enabled";
    public static final String INTENT_TTL_MINUTES = "intent_ttl_minutes";
    public static final String DISPLAY_NAME = "display_name";
  }

  /** Dedupe (mid, request_id). order_id used for order-payment mids (compare on duplicate). */
  public static final String WALLET_IDEMPOTENCY = "wallet_idempotency";

  public static final class WALLET_IDEMPOTENCY_ {
    public static final String MID = "mid";
    public static final String REQUEST_ID = "request_id";
    public static final String ORDER_ID = "order_id";
  }

  /** One row per accepted Sevlet wallet message. */
  public static final String WALLET_LEDGER = "wallet_ledger";

  public static final class WALLET_LEDGER_ {
    public static final String MID = "mid";
    public static final String REQUEST_ID = "request_id";
    public static final String ORDER_ID = "order_id";
    public static final String INPUT = "input";
    public static final String AMOUNT_MINOR = "amount_minor";
    public static final String DEBIT = "debit";
    public static final String CREDIT = "credit";
    public static final String CURRENCY_CODE = "currency_code";
    public static final String EXTRA_DATA = "extra_data";
    public static final String CREATED_AT = "created_at";
  }

  /** Initial intent and/or upsert after wallet_ledger settle; ON CONFLICT keeps order_id and created_at. */
  public static final String PAYMENT_LEDGER = "payment_ledger";

  public static final class PAYMENT_LEDGER_ {
    public static final String MID = "mid";
    public static final String REQUEST_ID = "request_id";
    public static final String ORDER_ID = "order_id";
    public static final String INPUT = "input";
    public static final String AMOUNT_MINOR = "amount_minor";
    public static final String DEBIT = "debit";
    public static final String CREDIT = "credit";
    public static final String CURRENCY_CODE = "currency_code";
    public static final String EXTRA_DATA = "extra_data";
    public static final String CREATED_AT = "created_at";
    public static final String INTENT_STATUS = "intent_status";
    public static final String EXPIRES_AT = "expires_at";
    public static final String CONFIRMED_AT = "confirmed_at";
    public static final String CONFIRM_CHALLENGE = "confirm_challenge";
    public static final String CANCEL_REASON = "cancel_reason";
  }

  /** wallet_account_hold table. */
  public static final String WALLET_ACCOUNT_HOLD = "wallet_account_hold";

  public static final class WALLET_ACCOUNT_HOLD_ {
    public static final String MID = "mid";
    public static final String REQUEST_ID = "request_id";
    public static final String ACCOUNT_ID = "account_id";
    public static final String AMOUNT_MINOR = "amount_minor";
    public static final String CREATED_AT = "created_at";
  }

  /** Journal voucher header; lines in wallet_journal_line. */
  public static final String WALLET_JOURNAL_ENTRY = "wallet_journal_entry";

  public static final class WALLET_JOURNAL_ENTRY_ {
    public static final String MID = "mid";
    public static final String REQUEST_ID = "request_id";
    public static final String ORDER_ID = "order_id";
    public static final String INPUT = "input";
    public static final String CURRENCY_CODE = "currency_code";
    public static final String EXTRA_DATA = "extra_data";
    public static final String CREATED_AT = "created_at";
  }

  /** Balanced lines: debit account / credit account for wire amount. */
  public static final String WALLET_JOURNAL_LINE = "wallet_journal_line";

  public static final class WALLET_JOURNAL_LINE_ {
    public static final String MID = "mid";
    public static final String REQUEST_ID = "request_id";
    public static final String LINE_NO = "line_no";
    public static final String ACCOUNT = "account";
    public static final String DEBIT_MINOR = "debit_minor";
    public static final String CREDIT_MINOR = "credit_minor";
  }
}
