#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
SCHEMA="$ROOT/src/main/resources/db/schema.sql"
OUT="$ROOT/src/main/java/dev/nivic/db/DbSchema.java"

mkdir -p "$(dirname "$OUT")"

cat > "$OUT" << 'JAVAHEAD'
package dev.nivic.db;

/**
 * Type-safe database constants generated from {@code src/main/resources/db/schema.sql}.
 *
 * <p>Each table has a nested class with column name constants and the table name itself.
 * Generated by {@code gen.sh} — do not edit manually.
 */
public final class DbSchema {

  private DbSchema() {}

JAVAHEAD

# Generate table constant + nested class from parsed metadata
emit_table() {
  local table_name="$1"    # e.g. wallet_mid_secret
  local comment="$2"       # SQL COMMENT ON TABLE
  local columns="$3"       # space-separated column names
  local col_comments="$4"  # pipe-separated "col:comment" pairs

  local const_name
  const_name=$(echo "$table_name" | tr '[:lower:]' '[:upper:]')

  echo "" >> "$OUT"
  if [[ -n "$comment" ]]; then
    echo "  /** ${comment} */" >> "$OUT"
  else
    echo "  /** ${table_name} table. */" >> "$OUT"
  fi
  echo "  public static final String ${const_name} = \"${table_name}\";" >> "$OUT"
  echo "" >> "$OUT"
  echo "  public static final class ${const_name}_ {" >> "$OUT"

  if [[ -n "$columns" ]]; then
    for col in $columns; do
      local col_upper
      col_upper=$(echo "$col" | tr '[:lower:]' '[:upper:]')
      # search for matching col comment
      local matched=""
      if [[ -n "$col_comments" ]]; then
        IFS='|' read -ra cc_pairs <<< "$col_comments"
        for pair in "${cc_pairs[@]+"${cc_pairs[@]}"}"; do
          local ccol="${pair%%:*}"
          local ccom="${pair#*:}"
          if [[ "$ccol" == "$col" && -n "$ccom" ]]; then
            matched="$ccom"
            break
          fi
        done
      fi
      if [[ -n "$matched" ]]; then
        echo "" >> "$OUT"
        echo "    /** ${matched} */" >> "$OUT"
      fi
      echo "    public static final String ${col_upper} = \"${col}\";" >> "$OUT"
    done
  fi
  echo "  }" >> "$OUT"
}

# Parse schema tables into temp files
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

TABLE_ORDER="wallet_mid_secret merchant_config wallet_idempotency wallet_ledger payment_ledger wallet_account_hold wallet_journal_entry wallet_journal_line"

# 1. Extract all COMMENT ON TABLE
grep -E "^COMMENT ON TABLE" "$SCHEMA" | while IFS="'" read -r prefix comment suffix; do
  tbl=$(echo "$prefix" | sed -n 's/COMMENT ON TABLE \([a-z_]*\) IS/\1/p' | tr -d ' ')
  echo "$tbl|$comment"
done > "$TMPDIR/table_comments.txt"

# 2. Extract all COMMENT ON COLUMN  
grep -E "^COMMENT ON COLUMN" "$SCHEMA" | while IFS="'" read -r prefix comment suffix; do
  rest=$(echo "$prefix" | sed -n 's/COMMENT ON COLUMN \([a-z_]*\)\.\([a-z_]*\) IS/\1|\2/p')
  tbl=$(echo "$rest" | cut -d'|' -f1)
  col=$(echo "$rest" | cut -d'|' -f2)
  echo "${tbl}.${col}|$comment"
done > "$TMPDIR/col_comments.txt"

# 3. Extract columns per table from CREATE TABLE blocks
rm -f "$TMPDIR/cols_"*
current_tbl=""
skip_to_semi=0
while IFS= read -r line; do
  if [[ "$line" =~ ^CREATE\ TABLE\ +(IF\ NOT\ EXISTS\ +)?([a-z_]+) ]]; then
    current_tbl="${BASH_REMATCH[2]}"
    skip_to_semi=0
    > "$TMPDIR/cols_${current_tbl}.txt"
  elif [[ -n "$current_tbl" && "$line" =~ ^\) ]] || [[ -n "$current_tbl" && "$line" =~ ^\;\ *$ ]]; then
    current_tbl=""
  elif [[ -n "$current_tbl" ]]; then
    # match column definition line: column_name TYPE
    trimmed=$(echo "$line" | sed 's/^[[:space:]]*//;s/,[[:space:]]*$//')
    if [[ "$trimmed" =~ ^([a-z_]+)\ +(BIGINT|INTEGER|BOOLEAN|BYTEA|VARCHAR|TIMESTAMPTZ|SMALLINT) ]]; then
      colname="${BASH_REMATCH[1]}"
      echo "$colname" >> "$TMPDIR/cols_${current_tbl}.txt"
    fi
  fi
done < "$SCHEMA"

# 4. Output each table
for tbl in $TABLE_ORDER; do
  cols_file="$TMPDIR/cols_${tbl}.txt"
  columns=""
  if [[ -f "$cols_file" ]]; then
    columns=$(tr '\n' ' ' < "$cols_file" | sed 's/ *$//')
  fi

  # Look up table comment
  tbl_comment=$(grep "^${tbl}|" "$TMPDIR/table_comments.txt" 2>/dev/null | sed "s/^${tbl}|//" | head -1 || echo "")

  # Build column comments string: col1:comment1|col2:comment2
  col_comments=""
  if [[ -n "$columns" ]]; then
    for col in $columns; do
      c=$(grep "^${tbl}\.${col}|" "$TMPDIR/col_comments.txt" 2>/dev/null | sed "s/^${tbl}\.${col}|//" | head -1 || echo "")
      if [[ -n "$c" ]]; then
        col_comments="${col_comments}|${col}:${c}"
      fi
    done
    col_comments="${col_comments#|}"
  fi

  emit_table "$tbl" "$tbl_comment" "$columns" "$col_comments"
done

echo "}" >> "$OUT"

echo "Generated $OUT"
