package codegen

import (
	"fmt"
	"io"
	"strings"

	"github.com/nivic/wire-gen/schema"
)

func GenerateC(p *schema.Protocol, w io.Writer) error {
	upper := strings.ToUpper(p.Name)
	b := &strings.Builder{}

	fmt.Fprintf(b, "/* Generated by wire-gen — do not edit */\n")
	fmt.Fprintf(b, "#pragma once\n")
	fmt.Fprintf(b, "#include <stdint.h>\n")
	fmt.Fprintf(b, "#include <stddef.h>\n\n")

	fmt.Fprintf(b, "/* %s offsets (bytes from frame start) */\n", p.Name)
	for _, f := range p.Fields {
		if f.Skip || f.Var {
			continue
		}
		fmt.Fprintf(b, "#define %s_OFFSET_%-20s %d\n",
			upper, f.ConstName(), f.Offset)
	}
	fmt.Fprintln(b)

	if vf := p.VarField(); vf != nil {
		fmt.Fprintf(b, "#define %s_PREFIX_LEN          %d\n", upper, p.PrefixLen)
		fmt.Fprintf(b, "#define %s_TRAILING_LEN        %d\n", upper, p.TrailingLen)
	}
	fmt.Fprintf(b, "#define %s_MIN_WIRE_LEN        %d\n", upper, p.MinWireLen)

	// trailing field sizes
	for _, f := range p.TrailingFields() {
		fmt.Fprintf(b, "#define %s_%-24s %d\n",
			upper, f.ConstName()+"_LEN", f.ByteSize())
	}
	fmt.Fprintln(b)

	// struct (fixed, non-skip, non-trailing fields + lengths)
	fmt.Fprintf(b, "typedef struct {\n")
	for _, f := range p.FixedFields() {
		if f.Trailing {
			continue
		}
		ctype := cType(f)
		fmt.Fprintf(b, "    %-12s %s;\n", ctype, f.Name)
	}
	if vf := p.VarField(); vf != nil {
		fmt.Fprintf(b, "    const uint8_t *%-12s /* points into raw buffer */;\n", vf.Name+";")
		fmt.Fprintf(b, "    uint32_t      %s_len;\n", vf.Name)
	}
	for _, f := range p.TrailingFields() {
		ctype := cType(f)
		fmt.Fprintf(b, "    %-12s %s;\n", ctype, f.Name)
	}
	fmt.Fprintf(b, "} %s;\n\n", p.Name)

	// decode function
	fmt.Fprintf(b, "/* Returns 0 on success, -1 if buf is too short. */\n")
	fmt.Fprintf(b, "static inline int %s_decode(\n", strings.ToLower(p.Name))
	fmt.Fprintf(b, "    const uint8_t *buf, size_t len, %s *out)\n{\n", p.Name)
	fmt.Fprintf(b, "    if (len < %s_MIN_WIRE_LEN) return -1;\n", upper)

	for _, f := range p.FixedFields() {
		if f.Trailing {
			continue
		}
		emitCRead(b, f, upper)
	}

	if vf := p.VarField(); vf != nil {
		fmt.Fprintf(b, "    out->%s_len = (uint32_t)(len - %s_MIN_WIRE_LEN);\n",
			vf.Name, upper)
		fmt.Fprintf(b, "    out->%s = buf + %s_PREFIX_LEN;\n", vf.Name, upper)
	}

	for _, f := range p.TrailingFields() {
		emitCReadTrailing(b, f, upper, p.PrefixLen)
	}

	fmt.Fprintf(b, "    return 0;\n}\n")

	_, err := io.WriteString(w, b.String())
	return err
}

func emitCRead(b *strings.Builder, f *schema.Field, upper string) {
	off := fmt.Sprintf("%s_OFFSET_%s", upper, f.ConstName())
	switch f.Type {
	case schema.TypeU8:
		fmt.Fprintf(b, "    out->%s = buf[%s];\n", f.Name, off)
	case schema.TypeU16:
		fmt.Fprintf(b, "    out->%s = (uint16_t)((buf[%s]<<8)|buf[%s+1]);\n", f.Name, off, off)
	case schema.TypeU32:
		fmt.Fprintf(b, "    out->%s = ((uint32_t)buf[%s]<<24)|((uint32_t)buf[%s+1]<<16)|((uint32_t)buf[%s+2]<<8)|(uint32_t)buf[%s+3];\n",
			f.Name, off, off, off, off)
	case schema.TypeU64:
		fmt.Fprintf(b, "    out->%s = ((uint64_t)buf[%s]<<56)|((uint64_t)buf[%s+1]<<48)|((uint64_t)buf[%s+2]<<40)|((uint64_t)buf[%s+3]<<32)|((uint64_t)buf[%s+4]<<24)|((uint64_t)buf[%s+5]<<16)|((uint64_t)buf[%s+6]<<8)|(uint64_t)buf[%s+7];\n",
			f.Name, off, off, off, off, off, off, off, off)
	case schema.TypeBytes:
		fmt.Fprintf(b, "    out->%s = buf + %s; /* %d bytes */\n", f.Name, off, f.Size)
	}
}

func emitCReadTrailing(b *strings.Builder, f *schema.Field, upper string, prefixLen int) {
	rel := f.Offset - prefixLen
	if rel == 0 {
		fmt.Fprintf(b, "    out->%s = buf + (len - %s_TRAILING_LEN);\n", f.Name, upper)
	} else {
		fmt.Fprintf(b, "    out->%s = buf + (len - %s_TRAILING_LEN + %d);\n", f.Name, upper, rel)
	}
}

func cType(f *schema.Field) string {
	switch f.Type {
	case schema.TypeU8:
		return "uint8_t"
	case schema.TypeU16:
		return "uint16_t"
	case schema.TypeU32:
		return "uint32_t"
	case schema.TypeU64:
		return "uint64_t"
	case schema.TypeBytes:
		return "const uint8_t *"
	}
	return "uint8_t"
}
