package codegen

import (
	"fmt"
	"io"
	"strings"

	"github.com/nivic/wire-gen/schema"
)

// goPackageName converts any string (e.g. "app.saving.wire") to a valid Go
// package identifier by taking the last dot-segment and lowercasing it.
func goPackageName(pkg, fallback string) string {
	if pkg == "" {
		return strings.ToLower(fallback)
	}
	parts := strings.Split(pkg, ".")
	return strings.ToLower(parts[len(parts)-1])
}

func GenerateGo(p *schema.Protocol, pkg string, w io.Writer) error {
	pkgName := goPackageName(pkg, p.Name)
	b := &strings.Builder{}

	fmt.Fprintf(b, "// Code generated by wire-gen — do not edit.\n\n")
	fmt.Fprintf(b, "package %s\n\n", pkgName)
	fmt.Fprintf(b, "import \"encoding/binary\"\n\n")

	// Offset / length constants
	fmt.Fprintf(b, "const (\n")
	for _, f := range p.Fields {
		if f.Skip || f.Var {
			continue
		}
		fmt.Fprintf(b, "\tOffset%-20s = %d\n", f.CamelCase(), f.Offset)
	}
	if p.VarField() != nil {
		fmt.Fprintf(b, "\tPrefixLen              = %d\n", p.PrefixLen)
		fmt.Fprintf(b, "\tTrailingLen            = %d\n", p.TrailingLen)
	}
	fmt.Fprintf(b, "\tMinWireLen             = %d\n", p.MinWireLen)
	for _, f := range p.TrailingFields() {
		fmt.Fprintf(b, "\t%sLen%s= %d\n",
			f.CamelCase(), strings.Repeat(" ", max(1, 24-len(f.CamelCase()))), f.ByteSize())
	}
	fmt.Fprintf(b, ")\n\n")

	// Struct: fixed non-trailing → var → trailing
	fmt.Fprintf(b, "type %s struct {\n", p.Name)
	for _, f := range p.FixedFields() {
		if f.Trailing {
			continue
		}
		fmt.Fprintf(b, "\t%-20s %s\n", f.CamelCase(), goType(f))
	}
	if vf := p.VarField(); vf != nil {
		fmt.Fprintf(b, "\t%-20s %s\n", vf.CamelCase(), goType(vf))
	}
	for _, f := range p.TrailingFields() {
		fmt.Fprintf(b, "\t%-20s %s\n", f.CamelCase(), goType(f))
	}
	fmt.Fprintf(b, "}\n\n")

	// Decode function
	fmt.Fprintf(b, "func Decode(raw []byte) (%s, error) {\n", p.Name)
	fmt.Fprintf(b, "\tif len(raw) < MinWireLen {\n")
	fmt.Fprintf(b, "\t\treturn %s{}, fmt.Errorf(\"frame too short: %%d\", len(raw))\n", p.Name)
	fmt.Fprintf(b, "\t}\n")
	fmt.Fprintf(b, "\tvar f %s\n", p.Name)

	for _, field := range p.FixedFields() {
		if field.Trailing {
			continue
		}
		emitGoRead(b, field)
	}

	if vf := p.VarField(); vf != nil {
		fmt.Fprintf(b, "\tf.%s = make([]byte, len(raw)-MinWireLen)\n", vf.CamelCase())
		fmt.Fprintf(b, "\tcopy(f.%s, raw[PrefixLen:len(raw)-TrailingLen])\n", vf.CamelCase())
	}

	for _, field := range p.TrailingFields() {
		emitGoReadTrailing(b, field, p.PrefixLen)
	}

	fmt.Fprintf(b, "\treturn f, nil\n}\n\n")

	// Peek helpers
	for _, field := range p.FixedFields() {
		if field.Trailing {
			continue
		}
		if field.Type == schema.TypeU64 && strings.Contains(strings.ToLower(field.Name), "mid") {
			fmt.Fprintf(b, "func Peek%s(raw []byte) uint64 {\n", field.CamelCase())
			fmt.Fprintf(b, "\treturn binary.BigEndian.Uint64(raw[Offset%s:])\n", field.CamelCase())
			fmt.Fprintf(b, "}\n\n")
		}
	}

	// Encode
	fmt.Fprintf(b, "func (f %s) Encode() []byte {\n", p.Name)
	if p.VarField() != nil {
		fmt.Fprintf(b, "\tout := make([]byte, MinWireLen+len(f.%s))\n", p.VarField().CamelCase())
	} else {
		fmt.Fprintf(b, "\tout := make([]byte, MinWireLen)\n")
	}
	for _, field := range p.FixedFields() {
		if field.Trailing {
			continue
		}
		emitGoWrite(b, field)
	}
	if vf := p.VarField(); vf != nil {
		fmt.Fprintf(b, "\tcopy(out[PrefixLen:], f.%s)\n", vf.CamelCase())
	}
	for _, field := range p.TrailingFields() {
		emitGoWriteTrailing(b, field, p.PrefixLen)
	}
	fmt.Fprintf(b, "\treturn out\n}\n")

	// fix: need fmt import if we use it
	result := b.String()
	if !strings.Contains(result, "fmt.Errorf") {
		result = strings.Replace(result, "import \"encoding/binary\"\n", "import \"encoding/binary\"\n", 1)
	} else {
		result = strings.Replace(result, "import \"encoding/binary\"\n", "import (\n\t\"encoding/binary\"\n\t\"fmt\"\n)\n", 1)
	}

	_, err := io.WriteString(w, result)
	return err
}

func emitGoRead(b *strings.Builder, f *schema.Field) {
	off := fmt.Sprintf("Offset%s", f.CamelCase())
	switch f.Type {
	case schema.TypeU8:
		fmt.Fprintf(b, "\tf.%s = raw[%s]\n", f.CamelCase(), off)
	case schema.TypeU16:
		fmt.Fprintf(b, "\tf.%s = binary.BigEndian.Uint16(raw[%s:])\n", f.CamelCase(), off)
	case schema.TypeU32:
		fmt.Fprintf(b, "\tf.%s = binary.BigEndian.Uint32(raw[%s:])\n", f.CamelCase(), off)
	case schema.TypeU64:
		fmt.Fprintf(b, "\tf.%s = binary.BigEndian.Uint64(raw[%s:])\n", f.CamelCase(), off)
	case schema.TypeBytes:
		fmt.Fprintf(b, "\tf.%s = make([]byte, %d)\n", f.CamelCase(), f.Size)
		fmt.Fprintf(b, "\tcopy(f.%s, raw[%s:%s+%d])\n", f.CamelCase(), off, off, f.Size)
	}
}

func emitGoReadTrailing(b *strings.Builder, f *schema.Field, prefixLen int) {
	rel := f.Offset - prefixLen // offset relative to start of trailing region
	switch f.Type {
	case schema.TypeBytes:
		fmt.Fprintf(b, "\tf.%s = make([]byte, %d)\n", f.CamelCase(), f.ByteSize())
		if rel == 0 {
			fmt.Fprintf(b, "\tcopy(f.%s, raw[len(raw)-TrailingLen:])\n", f.CamelCase())
		} else {
			fmt.Fprintf(b, "\tcopy(f.%s, raw[len(raw)-TrailingLen+%d:])\n", f.CamelCase(), rel)
		}
	default:
		if rel == 0 {
			fmt.Fprintf(b, "\tf.%s = raw[len(raw)-TrailingLen]\n", f.CamelCase())
		} else {
			fmt.Fprintf(b, "\tf.%s = raw[len(raw)-TrailingLen+%d]\n", f.CamelCase(), rel)
		}
	}
}

func emitGoWrite(b *strings.Builder, f *schema.Field) {
	off := fmt.Sprintf("Offset%s", f.CamelCase())
	switch f.Type {
	case schema.TypeU8:
		fmt.Fprintf(b, "\tout[%s] = f.%s\n", off, f.CamelCase())
	case schema.TypeU16:
		fmt.Fprintf(b, "\tbinary.BigEndian.PutUint16(out[%s:], f.%s)\n", off, f.CamelCase())
	case schema.TypeU32:
		fmt.Fprintf(b, "\tbinary.BigEndian.PutUint32(out[%s:], f.%s)\n", off, f.CamelCase())
	case schema.TypeU64:
		fmt.Fprintf(b, "\tbinary.BigEndian.PutUint64(out[%s:], f.%s)\n", off, f.CamelCase())
	case schema.TypeBytes:
		fmt.Fprintf(b, "\tcopy(out[%s:%s+%d], f.%s)\n", off, off, f.Size, f.CamelCase())
	}
}

func emitGoWriteTrailing(b *strings.Builder, f *schema.Field, prefixLen int) {
	rel := f.Offset - prefixLen
	switch f.Type {
	case schema.TypeBytes:
		if rel == 0 {
			fmt.Fprintf(b, "\tcopy(out[len(out)-TrailingLen:], f.%s)\n", f.CamelCase())
		} else {
			fmt.Fprintf(b, "\tcopy(out[len(out)-TrailingLen+%d:], f.%s)\n", rel, f.CamelCase())
		}
	default:
		if rel == 0 {
			fmt.Fprintf(b, "\tout[len(out)-TrailingLen] = f.%s\n", f.CamelCase())
		} else {
			fmt.Fprintf(b, "\tout[len(out)-TrailingLen+%d] = f.%s\n", rel, f.CamelCase())
		}
	}
}

func goType(f *schema.Field) string {
	switch f.Type {
	case schema.TypeU8:
		return "byte"
	case schema.TypeU16:
		return "uint16"
	case schema.TypeU32:
		return "uint32"
	case schema.TypeU64:
		return "uint64"
	case schema.TypeBytes:
		return "[]byte"
	}
	return "byte"
}

func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}
