package codegen

import (
	"fmt"
	"io"
	"strings"

	"github.com/nivic/wire-gen/schema"
)

func GenerateJava(p *schema.Protocol, pkg string, w io.Writer) error {
	b := &strings.Builder{}

	fmt.Fprintf(b, "/* Generated by wire-gen — do not edit */\n")
	if pkg != "" {
		fmt.Fprintf(b, "package %s;\n\n", pkg)
	}
	fmt.Fprintf(b, "import java.util.Arrays;\n\n")

	fmt.Fprintf(b, "public final class %sCodec {\n\n", p.Name)
	fmt.Fprintf(b, "  private %sCodec() {}\n\n", p.Name)

	// Offset constants
	fmt.Fprintf(b, "  /* Field offsets (bytes from frame start) */\n")
	for _, f := range p.Fields {
		if f.Skip || f.Var {
			continue
		}
		fmt.Fprintf(b, "  public static final int OFFSET_%-22s = %d;\n",
			f.ConstName(), f.Offset)
	}
	fmt.Fprintln(b)

	if p.VarField() != nil {
		fmt.Fprintf(b, "  public static final int PREFIX_LEN              = %d;\n", p.PrefixLen)
		fmt.Fprintf(b, "  public static final int TRAILING_LEN            = %d;\n", p.TrailingLen)
	}
	fmt.Fprintf(b, "  public static final int MIN_WIRE_LEN            = %d;\n", p.MinWireLen)
	for _, f := range p.TrailingFields() {
		fmt.Fprintf(b, "  public static final int %-24s = %d;\n",
			f.ConstName()+"_LEN", f.ByteSize())
	}
	fmt.Fprintln(b)

	// Record: fixed non-trailing → var → trailing
	fmt.Fprintf(b, "  public record Decoded(\n")
	var recFields []*schema.Field
	for _, f := range p.FixedFields() {
		if !f.Trailing {
			recFields = append(recFields, f)
		}
	}
	if vf := p.VarField(); vf != nil {
		recFields = append(recFields, vf)
	}
	recFields = append(recFields, p.TrailingFields()...)
	for i, f := range recFields {
		comma := ","
		if i == len(recFields)-1 {
			comma = ""
		}
		fmt.Fprintf(b, "      %s %s%s\n", javaType(f), f.LowerCamel(), comma)
	}
	fmt.Fprintf(b, "  ) {}\n\n")

	// peekMid / peekLong helper
	for _, f := range p.FixedFields() {
		if f.Trailing {
			continue
		}
		if f.Type == schema.TypeU64 && strings.Contains(strings.ToLower(f.Name), "mid") {
			fmt.Fprintf(b, "  /** Read %s without full decode — use before HMAC key lookup. */\n", f.CamelCase())
			fmt.Fprintf(b, "  public static long peek%s(byte[] raw) {\n", f.CamelCase())
			fmt.Fprintf(b, "    if (raw.length < MIN_WIRE_LEN) throw new IllegalArgumentException(\"too short\");\n")
			fmt.Fprintf(b, "    return readLong(raw, OFFSET_%s);\n", f.ConstName())
			fmt.Fprintf(b, "  }\n\n")
		}
	}

	// decode
	fmt.Fprintf(b, "  public static Decoded decode(byte[] raw) {\n")
	fmt.Fprintf(b, "    if (raw.length < MIN_WIRE_LEN)\n")
	fmt.Fprintf(b, "      throw new IllegalArgumentException(\"frame too short: \" + raw.length);\n")
	fmt.Fprintln(b)

	for _, f := range p.FixedFields() {
		if f.Trailing {
			continue
		}
		emitJavaRead(b, f)
	}

	if vf := p.VarField(); vf != nil {
		fmt.Fprintf(b, "    byte[] %s = Arrays.copyOfRange(raw, PREFIX_LEN, raw.length - TRAILING_LEN);\n",
			vf.LowerCamel())
	}

	for _, f := range p.TrailingFields() {
		emitJavaReadTrailing(b, f, p.PrefixLen)
	}
	fmt.Fprintln(b)

	// return order: fixed non-trailing → var → trailing
	fmt.Fprintf(b, "    return new Decoded(\n")
	var returnFields []*schema.Field
	for _, f := range p.FixedFields() {
		if !f.Trailing {
			returnFields = append(returnFields, f)
		}
	}
	if vf := p.VarField(); vf != nil {
		returnFields = append(returnFields, vf)
	}
	returnFields = append(returnFields, p.TrailingFields()...)
	for i, f := range returnFields {
		comma := ","
		if i == len(returnFields)-1 {
			comma = ""
		}
		fmt.Fprintf(b, "        %s%s\n", f.LowerCamel(), comma)
	}
	fmt.Fprintf(b, "    );\n  }\n\n")

	// read helpers
	fmt.Fprintf(b, "  private static long readLong(byte[] b, int off) {\n")
	fmt.Fprintf(b, "    return ((long)(b[off]&0xFF)<<56)|((long)(b[off+1]&0xFF)<<48)\n")
	fmt.Fprintf(b, "         |((long)(b[off+2]&0xFF)<<40)|((long)(b[off+3]&0xFF)<<32)\n")
	fmt.Fprintf(b, "         |((long)(b[off+4]&0xFF)<<24)|((long)(b[off+5]&0xFF)<<16)\n")
	fmt.Fprintf(b, "         |((long)(b[off+6]&0xFF)<< 8)|((long)(b[off+7]&0xFF));\n")
	fmt.Fprintf(b, "  }\n\n")

	fmt.Fprintf(b, "  private static int readInt(byte[] b, int off) {\n")
	fmt.Fprintf(b, "    return ((b[off]&0xFF)<<24)|((b[off+1]&0xFF)<<16)\n")
	fmt.Fprintf(b, "          |((b[off+2]&0xFF)<<8)|(b[off+3]&0xFF);\n")
	fmt.Fprintf(b, "  }\n\n")

	fmt.Fprintf(b, "  private static int readShort(byte[] b, int off) {\n")
	fmt.Fprintf(b, "    return ((b[off]&0xFF)<<8)|(b[off+1]&0xFF);\n")
	fmt.Fprintf(b, "  }\n")

	fmt.Fprintf(b, "}\n")

	_, err := io.WriteString(w, b.String())
	return err
}

func emitJavaReadTrailing(b *strings.Builder, f *schema.Field, prefixLen int) {
	rel := f.Offset - prefixLen
	switch f.Type {
	case schema.TypeBytes:
		if rel == 0 {
			fmt.Fprintf(b, "    byte[] %s = Arrays.copyOfRange(raw, raw.length - TRAILING_LEN, raw.length - TRAILING_LEN + %d);\n",
				f.LowerCamel(), f.ByteSize())
		} else {
			fmt.Fprintf(b, "    byte[] %s = Arrays.copyOfRange(raw, raw.length - TRAILING_LEN + %d, raw.length - TRAILING_LEN + %d);\n",
				f.LowerCamel(), rel, rel+f.ByteSize())
		}
	case schema.TypeU8:
		if rel == 0 {
			fmt.Fprintf(b, "    int %s = raw[raw.length - TRAILING_LEN] & 0xFF;\n", f.LowerCamel())
		} else {
			fmt.Fprintf(b, "    int %s = raw[raw.length - TRAILING_LEN + %d] & 0xFF;\n", f.LowerCamel(), rel)
		}
	case schema.TypeU16:
		if rel == 0 {
			fmt.Fprintf(b, "    int %s = readShort(raw, raw.length - TRAILING_LEN);\n", f.LowerCamel())
		} else {
			fmt.Fprintf(b, "    int %s = readShort(raw, raw.length - TRAILING_LEN + %d);\n", f.LowerCamel(), rel)
		}
	case schema.TypeU32:
		if rel == 0 {
			fmt.Fprintf(b, "    int %s = readInt(raw, raw.length - TRAILING_LEN);\n", f.LowerCamel())
		} else {
			fmt.Fprintf(b, "    int %s = readInt(raw, raw.length - TRAILING_LEN + %d);\n", f.LowerCamel(), rel)
		}
	case schema.TypeU64:
		if rel == 0 {
			fmt.Fprintf(b, "    long %s = readLong(raw, raw.length - TRAILING_LEN);\n", f.LowerCamel())
		} else {
			fmt.Fprintf(b, "    long %s = readLong(raw, raw.length - TRAILING_LEN + %d);\n", f.LowerCamel(), rel)
		}
	}
}

func emitJavaRead(b *strings.Builder, f *schema.Field) {
	off := fmt.Sprintf("OFFSET_%s", f.ConstName())
	switch f.Type {
	case schema.TypeU8:
		fmt.Fprintf(b, "    int %s = raw[%s] & 0xFF;\n", f.LowerCamel(), off)
	case schema.TypeU16:
		fmt.Fprintf(b, "    int %s = readShort(raw, %s);\n", f.LowerCamel(), off)
	case schema.TypeU32:
		fmt.Fprintf(b, "    int %s = readInt(raw, %s);\n", f.LowerCamel(), off)
	case schema.TypeU64:
		fmt.Fprintf(b, "    long %s = readLong(raw, %s);\n", f.LowerCamel(), off)
	case schema.TypeBytes:
		fmt.Fprintf(b, "    byte[] %s = Arrays.copyOfRange(raw, %s, %s + %d);\n",
			f.LowerCamel(), off, off, f.Size)
	}
}

func javaType(f *schema.Field) string {
	switch f.Type {
	case schema.TypeU8, schema.TypeU16:
		return "int"
	case schema.TypeU32:
		return "int"
	case schema.TypeU64:
		return "long"
	case schema.TypeBytes:
		return "byte[]"
	}
	return "int"
}
