package codegen

import (
	"fmt"
	"io"
	"strings"

	"github.com/nivic/wire-gen/schema"
)

func GenerateKotlin(p *schema.Protocol, pkg string, w io.Writer) error {
	b := &strings.Builder{}

	fmt.Fprintf(b, "/* Generated by wire-gen — do not edit */\n")
	if pkg != "" {
		fmt.Fprintf(b, "package %s\n\n", pkg)
	}

	// Companion constants
	fmt.Fprintf(b, "object %sProto {\n", p.Name)
	fmt.Fprintf(b, "    /* Field offsets (bytes from frame start) */\n")
	for _, f := range p.Fields {
		if f.Skip || f.Var {
			continue
		}
		fmt.Fprintf(b, "    const val OFFSET_%-22s = %d\n", f.ConstName(), f.Offset)
	}
	fmt.Fprintln(b)

	if p.VarField() != nil {
		fmt.Fprintf(b, "    const val PREFIX_LEN              = %d\n", p.PrefixLen)
		fmt.Fprintf(b, "    const val TRAILING_LEN            = %d\n", p.TrailingLen)
	}
	fmt.Fprintf(b, "    const val MIN_WIRE_LEN            = %d\n", p.MinWireLen)
	for _, f := range p.TrailingFields() {
		fmt.Fprintf(b, "    const val %-24s = %d\n", f.ConstName()+"_LEN", f.ByteSize())
	}
	fmt.Fprintln(b)

	// peek helpers
	for _, f := range p.FixedFields() {
		if f.Trailing {
			continue
		}
		if f.Type == schema.TypeU64 && strings.Contains(strings.ToLower(f.Name), "mid") {
			fmt.Fprintf(b, "    fun peek%s(raw: ByteArray): Long {\n", f.CamelCase())
			fmt.Fprintf(b, "        require(raw.size >= MIN_WIRE_LEN) { \"frame too short\" }\n")
			fmt.Fprintf(b, "        return readLong(raw, OFFSET_%s)\n", f.ConstName())
			fmt.Fprintf(b, "    }\n\n")
		}
	}

	// decode
	fmt.Fprintf(b, "    fun decode(raw: ByteArray): %s {\n", p.Name)
	fmt.Fprintf(b, "        require(raw.size >= MIN_WIRE_LEN) { \"frame too short: ${'$'}{raw.size}\" }\n")
	fmt.Fprintln(b)

	for _, f := range p.FixedFields() {
		if f.Trailing {
			continue
		}
		emitKotlinRead(b, f)
	}

	if vf := p.VarField(); vf != nil {
		fmt.Fprintf(b, "        val %s = raw.copyOfRange(PREFIX_LEN, raw.size - TRAILING_LEN)\n",
			vf.LowerCamel())
	}

	for _, f := range p.TrailingFields() {
		emitKotlinReadTrailing(b, f, p.PrefixLen)
	}

	fmt.Fprintln(b)
	fmt.Fprintf(b, "        return %s(\n", p.Name)
	// order must match data class: fixed non-trailing → var → trailing
	var allReturn []*schema.Field
	for _, f := range p.FixedFields() {
		if !f.Trailing {
			allReturn = append(allReturn, f)
		}
	}
	if vf := p.VarField(); vf != nil {
		allReturn = append(allReturn, vf)
	}
	allReturn = append(allReturn, p.TrailingFields()...)
	for i, f := range allReturn {
		comma := ","
		if i == len(allReturn)-1 {
			comma = ""
		}
		fmt.Fprintf(b, "            %s = %s%s\n", f.LowerCamel(), f.LowerCamel(), comma)
	}
	fmt.Fprintf(b, "        )\n    }\n\n")

	// read helpers
	fmt.Fprintf(b, "    private fun readShort(b: ByteArray, off: Int): Int =\n")
	fmt.Fprintf(b, "        ((b[off].toInt() and 0xFF) shl 8) or (b[off+1].toInt() and 0xFF)\n\n")

	fmt.Fprintf(b, "    private fun readInt(b: ByteArray, off: Int): Int =\n")
	fmt.Fprintf(b, "        ((b[off].toInt() and 0xFF) shl 24) or ((b[off+1].toInt() and 0xFF) shl 16) or\n")
	fmt.Fprintf(b, "        ((b[off+2].toInt() and 0xFF) shl 8) or (b[off+3].toInt() and 0xFF)\n\n")

	fmt.Fprintf(b, "    private fun readLong(b: ByteArray, off: Int): Long =\n")
	fmt.Fprintf(b, "        ((b[off].toLong() and 0xFF) shl 56) or ((b[off+1].toLong() and 0xFF) shl 48) or\n")
	fmt.Fprintf(b, "        ((b[off+2].toLong() and 0xFF) shl 40) or ((b[off+3].toLong() and 0xFF) shl 32) or\n")
	fmt.Fprintf(b, "        ((b[off+4].toLong() and 0xFF) shl 24) or ((b[off+5].toLong() and 0xFF) shl 16) or\n")
	fmt.Fprintf(b, "        ((b[off+6].toLong() and 0xFF) shl 8) or (b[off+7].toLong() and 0xFF)\n")

	fmt.Fprintf(b, "}\n\n")

	// data class: fixed non-trailing → var → trailing
	fmt.Fprintf(b, "data class %s(\n", p.Name)
	var dcFields []*schema.Field
	for _, f := range p.FixedFields() {
		if !f.Trailing {
			dcFields = append(dcFields, f)
		}
	}
	if vf := p.VarField(); vf != nil {
		dcFields = append(dcFields, vf)
	}
	dcFields = append(dcFields, p.TrailingFields()...)
	for i, f := range dcFields {
		comma := ","
		if i == len(dcFields)-1 {
			comma = ""
		}
		fmt.Fprintf(b, "    val %s: %s%s\n", f.LowerCamel(), kotlinType(f), comma)
	}
	fmt.Fprintf(b, ")\n")

	_, err := io.WriteString(w, b.String())
	return err
}

func emitKotlinRead(b *strings.Builder, f *schema.Field) {
	off := fmt.Sprintf("OFFSET_%s", f.ConstName())
	switch f.Type {
	case schema.TypeU8:
		fmt.Fprintf(b, "        val %s = raw[%s].toInt() and 0xFF\n", f.LowerCamel(), off)
	case schema.TypeU16:
		fmt.Fprintf(b, "        val %s = readShort(raw, %s)\n", f.LowerCamel(), off)
	case schema.TypeU32:
		fmt.Fprintf(b, "        val %s = readInt(raw, %s)\n", f.LowerCamel(), off)
	case schema.TypeU64:
		fmt.Fprintf(b, "        val %s = readLong(raw, %s)\n", f.LowerCamel(), off)
	case schema.TypeBytes:
		fmt.Fprintf(b, "        val %s = raw.copyOfRange(%s, %s + %d)\n",
			f.LowerCamel(), off, off, f.Size)
	}
}

func emitKotlinReadTrailing(b *strings.Builder, f *schema.Field, prefixLen int) {
	rel := f.Offset - prefixLen
	endBase := "raw.size - TRAILING_LEN"
	switch f.Type {
	case schema.TypeBytes:
		if rel == 0 {
			fmt.Fprintf(b, "        val %s = raw.copyOfRange(%s, %s + %d)\n",
				f.LowerCamel(), endBase, endBase, f.ByteSize())
		} else {
			fmt.Fprintf(b, "        val %s = raw.copyOfRange(%s + %d, %s + %d)\n",
				f.LowerCamel(), endBase, rel, endBase, rel+f.ByteSize())
		}
	default:
		if rel == 0 {
			fmt.Fprintf(b, "        val %s = raw[%s].toInt() and 0xFF\n",
				f.LowerCamel(), endBase)
		} else {
			fmt.Fprintf(b, "        val %s = raw[%s + %d].toInt() and 0xFF\n",
				f.LowerCamel(), endBase, rel)
		}
	}
}

func kotlinType(f *schema.Field) string {
	switch f.Type {
	case schema.TypeU8, schema.TypeU16, schema.TypeU32:
		return "Int"
	case schema.TypeU64:
		return "Long"
	case schema.TypeBytes:
		return "ByteArray"
	}
	return "Int"
}
