package codegen

import (
	"fmt"
	"io"
	"strings"

	"github.com/nivic/wire-gen/schema"
)

func GenerateSwift(p *schema.Protocol, w io.Writer) error {
	b := &strings.Builder{}

	fmt.Fprintf(b, "// Generated by wire-gen — do not edit\n")
	fmt.Fprintf(b, "import Foundation\n\n")

	// Offset constants
	fmt.Fprintf(b, "enum %sOffset {\n", p.Name)
	for _, f := range p.Fields {
		if f.Skip || f.Var {
			continue
		}
		fmt.Fprintf(b, "    static let %-22s = %d\n", swiftConstName(f.Name), f.Offset)
	}
	fmt.Fprintf(b, "}\n\n")

	// Length constants
	fmt.Fprintf(b, "enum %sLen {\n", p.Name)
	if p.VarField() != nil {
		fmt.Fprintf(b, "    static let prefixLen              = %d\n", p.PrefixLen)
		fmt.Fprintf(b, "    static let trailingLen            = %d\n", p.TrailingLen)
	}
	fmt.Fprintf(b, "    static let minWireLen             = %d\n", p.MinWireLen)
	for _, f := range p.TrailingFields() {
		fmt.Fprintf(b, "    static let %-22s = %d\n", swiftConstName(f.Name)+"Len", f.ByteSize())
	}
	fmt.Fprintf(b, "}\n\n")

	// Struct: fixed non-trailing → var → trailing
	fmt.Fprintf(b, "struct %s {\n", p.Name)
	for _, f := range p.FixedFields() {
		if f.Trailing {
			continue
		}
		fmt.Fprintf(b, "    let %s: %s\n", f.LowerCamel(), swiftType(f))
	}
	if vf := p.VarField(); vf != nil {
		fmt.Fprintf(b, "    let %s: %s\n", vf.LowerCamel(), swiftType(vf))
	}
	for _, f := range p.TrailingFields() {
		fmt.Fprintf(b, "    let %s: %s\n", f.LowerCamel(), swiftType(f))
	}
	fmt.Fprintf(b, "}\n\n")

	// Decoder extension
	fmt.Fprintf(b, "extension %s {\n", p.Name)
	fmt.Fprintf(b, "    static func decode(_ raw: Data) throws -> %s {\n", p.Name)
	fmt.Fprintf(b, "        guard raw.count >= %sLen.minWireLen else {\n", p.Name)
	fmt.Fprintf(b, "            throw WireError.frameTooShort(raw.count)\n")
	fmt.Fprintf(b, "        }\n")
	fmt.Fprintf(b, "        let b = [UInt8](raw)\n")

	for _, f := range p.FixedFields() {
		if f.Trailing {
			continue
		}
		emitSwiftRead(b, f, p.Name)
	}

	if vf := p.VarField(); vf != nil {
		fmt.Fprintf(b, "        let %s = Data(b[%sLen.prefixLen ..< b.count - %sLen.trailingLen])\n",
			vf.LowerCamel(), p.Name, p.Name)
	}

	for _, f := range p.TrailingFields() {
		emitSwiftReadTrailing(b, f, p.Name, p.PrefixLen)
	}

	fmt.Fprintf(b, "        return %s(\n", p.Name)
	// return order must match struct: fixed non-trailing → var → trailing
	var allReturn []*schema.Field
	for _, f := range p.FixedFields() {
		if !f.Trailing {
			allReturn = append(allReturn, f)
		}
	}
	if vf := p.VarField(); vf != nil {
		allReturn = append(allReturn, vf)
	}
	allReturn = append(allReturn, p.TrailingFields()...)
	for i, f := range allReturn {
		comma := ","
		if i == len(allReturn)-1 {
			comma = ""
		}
		fmt.Fprintf(b, "            %s: %s%s\n", f.LowerCamel(), f.LowerCamel(), comma)
	}
	fmt.Fprintf(b, "        )\n    }\n}\n\n")

	// peek helpers
	for _, f := range p.FixedFields() {
		if f.Trailing {
			continue
		}
		if f.Type == schema.TypeU64 && strings.Contains(strings.ToLower(f.Name), "mid") {
			fmt.Fprintf(b, "extension %s {\n", p.Name)
			fmt.Fprintf(b, "    static func peek%s(_ raw: Data) -> UInt64 {\n", f.CamelCase())
			fmt.Fprintf(b, "        let b = [UInt8](raw)\n")
			fmt.Fprintf(b, "        return readU64(b, %sOffset.%s)\n", p.Name, swiftConstName(f.Name))
			fmt.Fprintf(b, "    }\n}\n\n")
		}
	}

	// WireError
	fmt.Fprintf(b, "enum WireError: Error {\n")
	fmt.Fprintf(b, "    case frameTooShort(Int)\n")
	fmt.Fprintf(b, "}\n\n")

	// Read helpers (file-private)
	fmt.Fprintf(b, "private func readU16(_ b: [UInt8], _ off: Int) -> UInt16 {\n")
	fmt.Fprintf(b, "    UInt16(b[off]) << 8 | UInt16(b[off+1])\n")
	fmt.Fprintf(b, "}\n\n")

	fmt.Fprintf(b, "private func readU32(_ b: [UInt8], _ off: Int) -> UInt32 {\n")
	fmt.Fprintf(b, "    UInt32(b[off]) << 24 | UInt32(b[off+1]) << 16 | UInt32(b[off+2]) << 8 | UInt32(b[off+3])\n")
	fmt.Fprintf(b, "}\n\n")

	fmt.Fprintf(b, "private func readU64(_ b: [UInt8], _ off: Int) -> UInt64 {\n")
	fmt.Fprintf(b, "    UInt64(b[off]) << 56 | UInt64(b[off+1]) << 48 | UInt64(b[off+2]) << 40 | UInt64(b[off+3]) << 32\n")
	fmt.Fprintf(b, "        | UInt64(b[off+4]) << 24 | UInt64(b[off+5]) << 16 | UInt64(b[off+6]) << 8 | UInt64(b[off+7])\n")
	fmt.Fprintf(b, "}\n")

	_, err := io.WriteString(w, b.String())
	return err
}

func emitSwiftRead(b *strings.Builder, f *schema.Field, protoName string) {
	off := fmt.Sprintf("%sOffset.%s", protoName, swiftConstName(f.Name))
	switch f.Type {
	case schema.TypeU8:
		fmt.Fprintf(b, "        let %s = UInt8(b[%s])\n", f.LowerCamel(), off)
	case schema.TypeU16:
		fmt.Fprintf(b, "        let %s = readU16(b, %s)\n", f.LowerCamel(), off)
	case schema.TypeU32:
		fmt.Fprintf(b, "        let %s = readU32(b, %s)\n", f.LowerCamel(), off)
	case schema.TypeU64:
		fmt.Fprintf(b, "        let %s = readU64(b, %s)\n", f.LowerCamel(), off)
	case schema.TypeBytes:
		fmt.Fprintf(b, "        let %s = Data(b[%s ..< %s + %d])\n",
			f.LowerCamel(), off, off, f.Size)
	}
}

func emitSwiftReadTrailing(b *strings.Builder, f *schema.Field, protoName string, prefixLen int) {
	rel := f.Offset - prefixLen
	switch f.Type {
	case schema.TypeBytes:
		if rel == 0 {
			fmt.Fprintf(b, "        let %s = Data(b[(b.count - %sLen.trailingLen) ..< (b.count - %sLen.trailingLen) + %d])\n",
				f.LowerCamel(), protoName, protoName, f.ByteSize())
		} else {
			fmt.Fprintf(b, "        let %s = Data(b[(b.count - %sLen.trailingLen + %d) ..< (b.count - %sLen.trailingLen + %d)])\n",
				f.LowerCamel(), protoName, rel, protoName, rel+f.ByteSize())
		}
	default:
		if rel == 0 {
			fmt.Fprintf(b, "        let %s = b[b.count - %sLen.trailingLen]\n",
				f.LowerCamel(), protoName)
		} else {
			fmt.Fprintf(b, "        let %s = b[b.count - %sLen.trailingLen + %d]\n",
				f.LowerCamel(), protoName, rel)
		}
	}
}

func swiftType(f *schema.Field) string {
	switch f.Type {
	case schema.TypeU8:
		return "UInt8"
	case schema.TypeU16:
		return "UInt16"
	case schema.TypeU32:
		return "UInt32"
	case schema.TypeU64:
		return "UInt64"
	case schema.TypeBytes:
		return "Data"
	}
	return "UInt8"
}

func swiftConstName(name string) string {
	parts := strings.Split(name, "_")
	if len(parts) == 0 {
		return name
	}
	result := parts[0]
	for _, p := range parts[1:] {
		if len(p) > 0 {
			result += strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return result
}
